/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfazCliente.java
 *
 * Created on 1/06/2011, 05:32:43 PM
 */

package proyecto;

/**
 *
 * @author Jorge Morfinez Mojica
 *
 */
import java.net.*;
import java.io.*;

public class InterfazCliente extends javax.swing.JFrame {

    /** Creates new form InterfazCliente */
    public InterfazCliente() {
        initComponents();
        iniciarSocket();
        this.setLocation(250, 20);
        this.setResizable(false);
        //comunicarConServidor();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        foco4 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        licuadora = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        foco1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        foco3 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        foco2 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        foco5 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        television = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        foco6 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        foco8 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        clima1 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        foco9 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        clima2 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        foco7 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interfaz Cliente - Control del hogar");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Cocina", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco4.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco4.setText("Foco 4");
        foco4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco4ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        licuadora.setFont(new java.awt.Font("Tahoma", 0, 12));
        licuadora.setText("Licuadora");
        licuadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        licuadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licuadoraActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Licuadora.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(licuadora)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(foco4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel8)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foco4))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licuadora)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true), "Frente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12));

        foco1.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco1.setText("Foco 1");
        foco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        foco3.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco3.setText("Foco 3");
        foco3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        foco2.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco2.setText("Foco 2");
        foco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco2ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foco1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(59, 59, 59)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foco2)
                    .addComponent(jLabel5))
                .addGap(117, 117, 117)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(foco3))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foco3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(foco2)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(foco1))))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Sala", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco5.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco5.setText("Foco 5");
        foco5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco5ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        television.setFont(new java.awt.Font("Tahoma", 0, 12));
        television.setText("Televisión");
        television.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                televisionActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/electronics.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel9)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(television)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(foco5)
                                .addGap(13, 13, 13))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)))
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foco5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(television)
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/browser.png"))); // NOI18N
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/exit.png"))); // NOI18N
        jButton2.setText("Apagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Comedor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco6.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco6.setText("Foco 6");
        foco6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco6ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foco6)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foco6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Recamara 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco8.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco8.setText("Foco 8");
        foco8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco8ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        clima1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clima1.setText("Clima 1");
        clima1.setActionCommand("Clima 1");
        clima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clima1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foco8)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(clima1)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foco8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(clima1)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Recamara 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco9.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco9.setText("Foco 9");
        foco9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco9ActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        clima2.setFont(new java.awt.Font("Tahoma", 0, 12));
        clima2.setText("Clima 2");
        clima2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clima2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foco9)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(clima2)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foco9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(clima2)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Baño", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco7.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco7.setText("Foco 7");
        foco7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco7ActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(foco7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(foco7))
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/folder_home.png"))); // NOI18N
        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 13));
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/browser.png"))); // NOI18N
        jMenuItem4.setText("Enviar");
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/exit.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/advancedsettings.png"))); // NOI18N
        jMenu2.setText("Ayuda");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/khelpcenter.png"))); // NOI18N
        jMenuItem3.setText("Ayuda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/information.png"))); // NOI18N
        jMenuItem2.setText("Acerca de...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, 0, 205, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(437, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void foco4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco4ActionPerformed

    private void foco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco1ActionPerformed

    private void foco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco3ActionPerformed

    private void foco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco2ActionPerformed

    private void foco5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco5ActionPerformed

    private void licuadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licuadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licuadoraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        foco1.setSelected(false);
        foco2.setSelected(false);
        foco3.setSelected(false);
        foco4.setSelected(false);
        foco5.setSelected(false);
        foco5.setSelected(false);
        foco6.setSelected(false);
        foco7.setSelected(false);
        foco8.setSelected(false);
        foco9.setSelected(false);
        licuadora.setSelected(false);
        television.setSelected(false);
        clima1.setSelected(false);
        clima2.setSelected(false);
        
        //System.out.println(seleccionado);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //ClienteUDP cliente = new ClienteUDP("192.168.2.106");
        //seleccionado = foco1.isSelected();
        String mensaje;
        if(foco1.isSelected()){
          //System.out.println(" El foco 1 se ha encendido!");
           foco1a=true;
           foco_a=1;
           //mensaje = " El foco 1 ha sido seleccionado";
           //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(foco2.isSelected()){
            //System.out.println("El foco 2 se ha encendido!");
            foco2a=true;
            foco_b=1;
            //mensaje = " El foco 2 ha sido seleccionado";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(foco3.isSelected()){
            foco3a=true;
            foco_c=1;
            //mensaje = " El foco 3 ha sido seleccionado";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(foco4.isSelected()){
            foco4a=true;
            foco_d=1;
            //mensaje = " El foco 4 ha sido seleccionado";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(foco5.isSelected()){
            foco5a=true;
            foco_e=1;
            //mensaje = " El foco 5 ha sido seleccionado";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(foco6.isSelected()){
            foco6a=true;
            foco_f=1;
            //mensaje = " El foco 6 ha sido seleccionado";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(foco7.isSelected()){
            foco7a=true;
            foco_g=1;
            //mensaje = " El foco 7 ha sido seleccionado";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(foco8.isSelected()){
            foco8a=true;
            foco_h=1;
            //mensaje = " El foco 8 ha sido seleccionado";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(foco9.isSelected()){
            foco9a=true;
            foco_i=1;
            //mensaje = " El foco 9 ha sido seleccionado";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } 
        if(licuadora.isSelected()){
            //mensaje = " La licuadora ha sido seleccionada";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(television.isSelected()){
            //mensaje = " La televisión ha sido seleccionada";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(clima1.isSelected()){
            //mensaje = " El clima 2 ha sido seleccionado";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        if(clima2.isSelected()){
            //mensaje = " El clima 3 ha sido seleccionada";
            //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        int[] f = {foco_a, foco_b, foco_c, foco_d, foco_e, foco_f, foco_g, foco_h};
        focos = f;
        for(int i=0; i<f.length; i++)
        {
            String m="";
            if(focos[i]!=0){
                 //m=" Los focos seleccionados son: " + focos[i] + " foco: " + (i+1);
                 System.out.println(" Los elementos seleccionados son: " + focos[i] + " elemento: " + (i+1));
                 //javax.swing.JOptionPane.showMessageDialog(null, " Los focos seleccionados son, foco: " + (i+1), " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
        //COMPROBACION DE VARIOS ELEMENTOS SELECCIONADOS:
        /*
        int aux1=0;
        int [] fo = new int[8];
        for(int i=0; i<elementos.length; i++)
        {
            if(elementos[i].isSelected())
            {
                while(i<=8)
                {
                    fo[i]=1;
                    if(fo[i]!=0)
                    {
                        System.out.println(" Los elementos seleccionados son: " + elementos[i] + " elemento: " + (i+1));
                    }
                }
            }
            else
            {
                if(!elementos[i].isSelected())
                {
                    while(i<=8)
                    {
                       fo[i]=0;
                       if(fo[i]==0)
                       {
                           System.out.println(" Los elementos no seleccionados son: " + elementos[i] + " elemento: " + (i+1));
                       }
                    }
                }
            }
        }*/
        comunicarConServidor(focos);
        //comunicarConServidor(fo);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void iniciarSocket()
	{
            try
            {
            //Se asigna una máquina que será el servidor
            //se hace la conexión al servidor por el nombre y el puerto
                cliente = new Socket(servidor, port);
            }
        catch (IOException ioe)
        {
            javax.swing.JOptionPane.showMessageDialog(null, " Falló la conexión con el Servidor y/o el Puerto ", " Error de conexión", javax.swing.JOptionPane.ERROR_MESSAGE);
            //System.err.println(" Fallo la conexion con el servidor y/o el puerto, impreso en un System");
            System.exit(0);
        }
	}
	public void comunicarConServidor(int [] focoss)
	{
            try
            {
            // getInputStream() da el flujo de entrada de bytes
            // InputStreamReader convierte un flujo de byte a flujo de caracteres
            // BufferedReader permite leer lineas completas:
            InputStream flujoBE   = cliente.getInputStream();
            Reader flujoCE        = new InputStreamReader(flujoBE);
            BufferedReader reader = new BufferedReader(flujoCE);

            //se asocia un flujo de salida al cliente
            //con getOutputStream():
            OutputStream flujoBS  = cliente.getOutputStream();
            Writer flujoCS        = new OutputStreamWriter(cliente.getOutputStream());
            BufferedWriter writer = new BufferedWriter(flujoCS);

            //envia su nombre de host al servidor:
            //String mensaje=" Soy Xavier Morfinez";
            int [] arreglo = new int[8];
            arreglo=focoss;
            //String mensaje = String.valueOf(arreglo);
            String [] mensaje = new String[8];
            //mensaje.valueOf(arreglo);
            for(int i=0; i<arreglo.length; i++)
            {
            	mensaje[i] = ""+arreglo[i];
                //System.out.println(" El cliente envio: foco[" + (i+1) + "] = " + mensaje[i] + " Impreso de un System!");
                        //String.valueOf(", el cliente envio: foco [" + (i+1) + "] = " + arreglo[i] + "\n");

            //	writer.write("Hola soy: "+InetAddress.getLocalHost() + ", el cliente envio: foco[ " + (i+1) + "] = " + arreglo[i] + "\n");
            }
            String mensaje2="";
            for(int i=0; i<arreglo.length; i++)
            {
                mensaje2+=mensaje[i] + ",";
            	//writer.write(" Hola soy: "+InetAddress.getLocalHost() + ", el cliente envio: foco[ " + (i+1) + "] = " + mensaje[i]);
                //System.out.println(" El cliente envio: foco[" + (i+1) + "] = " + mensaje[i]);
            }
            
            InetAddress host = InetAddress.getByName(servidor);
            String nombre = host.getHostAddress();
            String ip = host.getHostName();
            //System.out.println(" Mensaje que envio impreso en un System: " + mensaje2);
            //writer.write(mensaje + "\n");
            //int cont=1;
            //writer.write(" Hola soy: "+nombre + "\n");
            //writer.flush();
            //System.out.println("IP: " + ip + " \n Datos: " + mensaje2 + " Impreso de un System! \n");
            //writer.write(" IP: " + ip + "\n");
            //writer.flush();
            writer.write(mensaje2 + "\n");
            writer.flush();

            //String entrada="";
            //do
           // {
            //    entrada = reader.readLine();
            //    System.out.println("Recibido: " + entrada);
           // }
           // while(entrada.length()>1);
        }
        catch (IOException ioe)
        {
            javax.swing.JOptionPane.showMessageDialog(null, " ¡Error en el envío de la información! ", " Error de envío de información", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            //System.out.println(" Error en el envio de la informacion!: " + ioe + " Impreso en un System");
        }
    }
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int rest = 0;
        Object [] opciones = {"Si", "No"};
        rest = javax.swing.JOptionPane.showOptionDialog(this, "¿Desea salir de la aplicación?", "¿Salir?", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        if(rest==0)
            System.exit(0);
        else {
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void televisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_televisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_televisionActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void foco6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco6ActionPerformed

    private void foco8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco8ActionPerformed

    private void clima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clima1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clima1ActionPerformed

    private void foco9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco9ActionPerformed

    private void clima2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clima2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clima2ActionPerformed

    private void foco7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco7ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
                                                    //AYUDA:
        String instrucciones;
        instrucciones  = " Escriba, en el mensaje de diálogo, la dirección IP del Servidor que \n";
        instrucciones += " enciende las dispositivos eléctricos-electrónicos.\n";
        instrucciones += " Seleccione los elementos que quiera que se enciendan para \n";
        instrucciones += " enviarse al Servidor. \n";
        instrucciones += " Seleccione solamente hasta 8 elementos, desde el Foco 1 hasta el 8\n";
        instrucciones += " De clic en el botón Enviar.\n";
        instrucciones += " Para apagar los elementos, de clic en el botón Apagar.\n";
        instrucciones += " En el menú Inicio, haga clic en la opción Salir \n";
        instrucciones += " para salir de la aplicación, el sistema le preguntará si desea salir.\n";

        javax.swing.JOptionPane.showMessageDialog(null, instrucciones, " Instrucciones", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         //ACERCA DE...
        String creditos;
        creditos = " \nAplicación: Domótica AppClient™ Versión 1.0\n";
        creditos += " Fecha de creación: 13 de Junio de 2011\n";
        creditos += " Copyright © Morfínez Mojica Jorge,\n";
        creditos += " García Almanza Irving Rafael & \n Verdejo Bueno";
        creditos += " Carlos Adiel. \n";
        creditos += " ® Todos los derechos reservados.\n\n";
        creditos += " Aplicación controlada y supervizada por el\n";
        creditos += " Prof. Dr. Mejía Pérez Juan Francisco. \n";
        creditos += " Materia: Interfaces - 6H6C. \n";
        creditos += " Especialidad: Ing. en Sistemas Computacionales \n\n";
        creditos += "        Instituto Tecnológico de Veracruz\n";
        creditos += "    'Antorcha y Luz de Fuego Permanente'\n\n";

        javax.swing.JOptionPane.showMessageDialog(null, creditos, " Acerca de Domótica AppClient™", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                servidor = javax.swing.JOptionPane.showInputDialog(" Introduzca la dirección IP de su Servidor: ");
                new Thread(new VentanaSplash()).start();
                javax.swing.JOptionPane.showMessageDialog(null, " Seleccione solamente hasta 8 elementos, desde el Foco 1 al 8 ", " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                new InterfazCliente().setVisible(true);
                
                //System.out.println(" IP: " + servidor);
                //javax.swing.JOptionPane.showMessageDialog(null, mensaje, " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                //javax.swing.JOptionPane.showInputDialog(servidor);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox clima1;
    public javax.swing.JCheckBox clima2;
    public javax.swing.JCheckBox foco1;
    public javax.swing.JCheckBox foco2;
    public javax.swing.JCheckBox foco3;
    private javax.swing.JCheckBox foco4;
    public javax.swing.JCheckBox foco5;
    public javax.swing.JCheckBox foco6;
    public javax.swing.JCheckBox foco7;
    public javax.swing.JCheckBox foco8;
    public javax.swing.JCheckBox foco9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JCheckBox licuadora;
    public javax.swing.JCheckBox television;
    // End of variables declaration//GEN-END:variables
    public boolean seleccionado;
    public int foco_a=0;
    public int foco_b=0;
    public int foco_c=0;
    public int foco_d=0;
    public int foco_e=0;
    public int foco_f=0;
    public int foco_g=0;
    public int foco_h=0;
    public int foco_i=0;
    public int clima_a=0;
    public int clima_b=0;
    public int clima_c=0;
    public int focos[] = new int[8];
    public javax.swing.JCheckBox [] elementos = {foco1, foco2, foco3, foco4, foco5, foco6, foco7, foco8, foco9, clima1, clima2, licuadora, television};
    public boolean foco1a=false;
    public boolean foco2a=false;
    public boolean foco3a=false;
    public boolean foco4a=false;
    public boolean foco5a=false;
    public boolean foco6a=false;
    public boolean foco7a=false;
    public boolean foco8a=false;
    public boolean foco9a=false;
    //private String         servidor="192.168.1.109";
    private InetAddress    host;
    //public int puerto=5000;
    private int port = 5000;
    private Socket cliente = null;
    private static String servidor="";
}