/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfazCliente.java
 *
 * Created on 1/06/2011, 05:32:43 PM
 */

package proyecto;

/**
 *
 * @author Jorge Morfinez Mojica
 *
 */
import java.net.*;
import java.io.*;
import java.util.StringTokenizer;

public class InterfazServidor extends javax.swing.JFrame {

    /** Creates new form InterfazCliente */
    public InterfazServidor() {
        this.setLocation(250, 20);
        this.setSize(673, 668);
        initComponents();
        //iniciarSockets();
        iniciarConexion();
        comunicarConCliente();
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        foco4 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        licuadora = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        foco1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        foco3 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        foco2 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        foco5 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        television = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        foco6 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        foco9 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        clima2 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        foco7 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        foco10 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        clima3 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interfaz Servidor - Control del hogar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Cocina", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco4.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco4.setText("Foco 4");
        foco4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco4ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        licuadora.setFont(new java.awt.Font("Tahoma", 0, 12));
        licuadora.setText("Licuadora");
        licuadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        licuadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licuadoraActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Licuadora.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(foco4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(licuadora)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foco4))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(licuadora)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true), "Frente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12));

        foco1.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco1.setText("Foco 1");
        foco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        foco3.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco3.setText("Foco 3");
        foco3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        foco2.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco2.setText("Foco 2");
        foco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco2ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foco1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(57, 57, 57)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foco2)
                    .addComponent(jLabel5))
                .addGap(121, 121, 121)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(foco3))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foco2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foco1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foco3)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Sala", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco5.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco5.setText("Foco 5");
        foco5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco5ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        television.setFont(new java.awt.Font("Tahoma", 0, 12));
        television.setText("Televisión");
        television.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                televisionActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/electronics.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(foco5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(television)))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(foco5))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(television)
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/exit.png"))); // NOI18N
        jButton2.setText("Apagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Comedor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco6.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco6.setText("Foco 6");
        foco6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco6ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(foco6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(335, 335, 335)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(foco6))
                            .addComponent(jSeparator18, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Recamara 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco9.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco9.setLabel("Foco 8");
        foco9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco9ActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        clima2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clima2.setText("Clima 1");
        clima2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clima2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foco9)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(clima2)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foco9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(clima2)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Baño", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco7.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco7.setText("Foco 7");
        foco7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco7ActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(foco7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foco7))
                    .addComponent(jSeparator14, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true), "Recamara 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        foco10.setFont(new java.awt.Font("Tahoma", 0, 12));
        foco10.setText("Foco 9");
        foco10.setActionCommand("Foco 10");
        foco10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foco10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foco10ActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/ktip.png"))); // NOI18N

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);

        clima3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clima3.setText("Clima 2");
        clima3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clima3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(foco10))
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(clima3)
                .addGap(63, 63, 63))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foco10))
                    .addComponent(jSeparator16, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(clima3)
                .addContainerGap())
        );

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/browser.png"))); // NOI18N
        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/folder_home.png"))); // NOI18N
        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 13));
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/browser.png"))); // NOI18N
        jMenuItem4.setLabel("Aceptar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/exit.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/advancedsettings.png"))); // NOI18N
        jMenu2.setText("Ayuda");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 12));

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/khelpcenter.png"))); // NOI18N
        jMenuItem3.setText("Ayuda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/information.png"))); // NOI18N
        jMenuItem2.setText("Acerca de...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void foco4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco4ActionPerformed

    private void foco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco1ActionPerformed

    private void foco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco3ActionPerformed

    private void foco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco2ActionPerformed

    private void foco5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco5ActionPerformed

    private void licuadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licuadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licuadoraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        foco1.setSelected(false);
        foco2.setSelected(false);
        foco3.setSelected(false);
        foco4.setSelected(false);
        foco5.setSelected(false);
        foco5.setSelected(false);
        foco6.setSelected(false);
        foco7.setSelected(false);
        foco9.setSelected(false);
        foco10.setSelected(false);
        licuadora.setSelected(false);
        television.setSelected(false);
        clima2.setSelected(false);
        clima3.setSelected(false);
        
        //System.out.println(seleccionado);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void iniciarConexion()
    {
        try
        {
            //creando el socket y abriendo el puerto
            //port determina el número de puerto que se utiliza
            server = new ServerSocket(port);

            //getLocalHost obtiene la IP de la máquina:
            host = InetAddress.getLocalHost();
	    //System.out.println("\n  IP    : " + host.getHostAddress());
	    //System.out.println("  Nombre: " + host.getHostName());
			//getLocalPort obtiene el puerto asociado al socket:
            //System.out.println(" El puerto utilizado por el socket es: " + server.getLocalPort() + " Impreso de un System!");

        }
        catch (IOException ioe)
        {
            javax.swing.JOptionPane.showMessageDialog(null, "No se puede correr en el Puerto: "+port, " Error de conexión al puerto", javax.swing.JOptionPane.ERROR_MESSAGE);
            //System.err.println("No se puede correr en el puerto "+port + " Impreso en System!");
            System.exit(0);
        }
    }

    public void comunicarConCliente()
    {
        Archivo archi = new Archivo();
        try
        {
            //Al encontrar una petición de conexion esta se acepta:
            //System.out.println(" En espera de un cliente! Impreso en un System");
            //javax.swing.JOptionPane.showMessageDialog(null, " ¡En espera de un Cliente! ", " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
	    conexion = server.accept();
            //javax.swing.JOptionPane.showMessageDialog(null, " ¡Un Cliente llegó! ", " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
	    //System.out.println("\n Un cliente llego! Impreso en un System");
            //System.out.println(" Acepta conexión!!! Impreso en un System");
            //QUITARLE EL COMENTARIO A LA LINEA:
            //COMENTAR PARA QUE ENCIENDAN TODOS LOS ELEMENTOS:
            //javax.swing.JOptionPane.showMessageDialog(null, " ¡Acepta conexión! ", " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            //se asocia a un flujo al cliente que solicita la conexion
            // getInputStream() da el flujo de entrada de bytes
            // InputStreamReader convierte un flujo de byte a flujo de caracteres
            // BufferedReader permite leer lineas completas:
            //System.out.println(" EL SERVIDOR COMIENZA A RECIBIR PAQUETES!!!");

            InputStream flujoBE   = conexion.getInputStream();
            Reader flujoCE        = new InputStreamReader(flujoBE);
            BufferedReader reader = new BufferedReader(flujoCE);
            mensajeEnviado=reader.readLine();
            System.out.println(mensajeEnviado);
            File archivo = archi.escribirArchivo(mensajeEnviado);

            String [] arreglos;
            arreglos = Archivo.leerCadenas("datosfocos.txt");
            /*
            for(int i=0; i<16; i++)
            {
                arreglos[i]=mensajeEnviado.substring(0, i);

                System.out.println(arreglos[i]);
            }
            */
            for(int i=0; i<arreglos.length; i++)
            {
                int contaux=0;
                if(i==contaux)
	        {
               	        String aux = arreglos[contaux];
			   	  StringTokenizer token1 = new StringTokenizer(aux,",");
		                  while(token1.hasMoreTokens())
				  {
				        aux = token1.nextToken();
				        focoa = Integer.parseInt(aux);
                                        System.out.println(" foco1: " + focoa);
				        aux = token1.nextToken();
                       			focob = Integer.parseInt(aux);
                                        System.out.println(" foco2: " + focob);
					aux = token1.nextToken();
                       			fococ = Integer.parseInt(aux);
                                        System.out.println(" foco3: " + fococ);
                     			aux = token1.nextToken();
                      		        focod = Integer.parseInt(aux);
                                        System.out.println(" foco4: " + focod);
		                        aux = token1.nextToken();
                 		        focoe = Integer.parseInt(aux);
                                        System.out.println(" foco5: " + focoe);
		                        aux = token1.nextToken();
                  		        focof = Integer.parseInt(aux);
                                        System.out.println(" foco6: " + focof);
                                        aux = token1.nextToken();
                  		        focog = Integer.parseInt(aux);
                                        System.out.println(" foco7: " + focog);
                                        aux = token1.nextToken();
                  		        focoh = Integer.parseInt(aux);
                                        System.out.println(" foco8: " + focoh);
                                        int [] focos_s = {focoa, focob, fococ, focod, focoe, focof, focog, focoh};
                                        focos = focos_s;
				  }
				  contaux++;
			    }
            }

            for(int i=0; i<focos.length; i++)
            {
                if(focos[i]!=0)
                {
                    //javax.swing.JOptionPane.showMessageDialog(null, " Los elementos seleccionados son, elemento: " + (i+1), " Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    System.out.println(" Los elementos seleccionados son, elemento: " + (i+1));
                }   
                switch(i)
                {
                    case 0:{
                            if(focos[i]==1)
                            {
                                foco1.setSelected(true);
                                dato_circuito=1;
                            }
                            else{
                                foco1.setSelected(false);

                            }
                    }
                    break;
                    case 1:{
                            if(focos[i]==1)
                            {
                                foco2.setSelected(true);
                                dato_circuito+=2;
                            }
                            else{
                                foco2.setSelected(false);

                            }
                    }
                    break;
                    case 2:{
                            if(focos[i]==1)
                            {
                                foco3.setSelected(true);
                                dato_circuito+=4;
                            }
                            else{
                                foco3.setSelected(false);

                            }
                    }
                    break;
                    case 3:{
                            if(focos[i]==1)
                            {
                                foco4.setSelected(true);
                                dato_circuito+=8;
                            }
                            else{
                                foco4.setSelected(false);

                            }
                    }
                    break;
                    case 4:{
                            if(focos[i]==1)
                            {
                                foco5.setSelected(true);
                                dato_circuito+=16;
                            }
                            else{
                                foco5.setSelected(false);

                            }
                    }
                    break;
                    case 5:{
                            if(focos[i]==1)
                            {
                                foco6.setSelected(true);
                                dato_circuito+=32;
                            }
                            else{
                                foco6.setSelected(false);

                            }
                    }
                    break;
                    case 6:{
                            if(focos[i]==1)
                            {
                                foco7.setSelected(true);
                                dato_circuito+=64;
                            }
                            else{
                                foco7.setSelected(false);

                            }
                    }
                    break;
                    case 7:{
                            if(focos[i]==1)
                            {
                                foco9.setSelected(true);
                                dato_circuito+=128;
                            }
                            else{
                                foco9.setSelected(false);

                            }
                    }
                    break;
                }
            }

            System.out.print(" El dato que se pasa al circuito es: " + dato_circuito);

            //se cierran los flujos
            reader.close();
            //writer.close();
            //se cierra la conexión
            conexion.close();
            //System.out.println(" EL SERVIDOR TERMINA DE RECIBIR PAQUETES y TERMINA LA CONEXION!!!");
        }
        catch (IOException ioe1)
        {
            javax.swing.JOptionPane.showMessageDialog(null, " ¡Error en el recibo de la información del Cliente! ", " Error de envío de información", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            //System.out.println(" Error en el recibo de la informacion! " + ioe1);
        }
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int rest = 0;
        Object [] opciones = {"Si", "No"};
        rest = javax.swing.JOptionPane.showOptionDialog(this, "¿Desea salir de la aplicación?", "¿Salir?", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        if(rest==0)
            System.exit(0);
        else {
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void televisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_televisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_televisionActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void foco6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco6ActionPerformed

    private void foco9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco9ActionPerformed

    private void clima2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clima2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clima2ActionPerformed

    private void foco7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco7ActionPerformed

    private void foco10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foco10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foco10ActionPerformed

    private void clima3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clima3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clima3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
                                               //AYUDA:
        String instrucciones;
        instrucciones = "  De clic en Aceptar al mensaje: '¡Acepta conexión!' \n";
        instrucciones += " Esto quiere decir que acepta la conexión con el cliente. \n";
        instrucciones += " Enseguida aparecerá un mensaje diciéndole qué elementos se \n";
        instrucciones += " encendieron, de clic en Aceptar para aceptar que en realidad \n";
        instrucciones += " esos elementos se enviaron desde el cliente. \n";
        instrucciones += " A continuación aparecerá la pantalla con los elementos que se \n";
        instrucciones += " tienen en la propiedad y aparecerán seleccionados los mismos que \n";
        instrucciones += " le envió el Cliente. \n";
        instrucciones += " Una ves que vio que los elementos ya están encendidos, en el menú \n";
        instrucciones += " Inicio puede dar clic en la opción Aceptar para verificarle a la \n";
        instrucciones += " aplicación que está de acuerdo. \n\n";
        instrucciones += " De clic en el botón Apagar para deseleccionar y apagar los \n";
        instrucciones += " elementos enviados y seleccionados.\n";
        instrucciones += " En el menú Inicio, haga clic en la opción Salir \n";
        instrucciones += " para salir de la aplicación, el sistema le preguntará si desea salir.\n";

        javax.swing.JOptionPane.showMessageDialog(null, instrucciones, " Instrucciones", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         //ACERCA DE...
        String creditos;
        creditos = " \nAplicación: Domótica AppServer™ Versión 1.0\n";
        creditos += " Fecha de creación: 13 de Junio de 2011\n";
        creditos += " Copyright © Morfínez Mojica Jorge,\n";
        creditos += " García Almanza Irving Rafael & Verdejo Bueno.\n";
        creditos += " Carlos Adiel. \n";
        creditos += " ® Todos los derechos reservados.\n\n";
        creditos += " Aplicación controlada y supervizada por el\n";
        creditos += " Prof. Dr. Mejía Pérez Juan Francisco. \n";
        creditos += " Materia: Interfaces - 6H6C. \n";
        creditos += " Especialidad: Ing. en Sistemas Computacionales \n\n";
        creditos += "        Instituto Tecnológico de Veracruz\n";
        creditos += "    'Antorcha y Luz de Fuego Permanente'\n\n";

        javax.swing.JOptionPane.showMessageDialog(null, creditos, " Acerca de Domótica AppServer™", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Thread(new VentanaServidor()).start();
                new InterfazServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox clima2;
    public javax.swing.JCheckBox clima3;
    public javax.swing.JCheckBox foco1;
    public javax.swing.JCheckBox foco10;
    public javax.swing.JCheckBox foco2;
    public javax.swing.JCheckBox foco3;
    private javax.swing.JCheckBox foco4;
    public javax.swing.JCheckBox foco5;
    public javax.swing.JCheckBox foco6;
    public javax.swing.JCheckBox foco7;
    public javax.swing.JCheckBox foco9;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JCheckBox licuadora;
    public javax.swing.JCheckBox television;
    // End of variables declaration//GEN-END:variables
    public static String mensajeEnviado;
    public boolean seleccionado;
    
    public int focoa;
    public int focob;
    public int fococ;
    public int focod;
    public int focoe;
    public int focof;
    public int focog;
    public int focoh;
    public int dato_circuito=0;

    public int focos[] = new int[8];
    public boolean foco1a=false;
    public boolean foco2a=false;
    public boolean foco3a=false;
    public boolean foco4a=false;
    public boolean foco5a=false;
    public boolean foco6a=false;
    public boolean foco7a=false;
    public boolean foco8a=false;
    public boolean foco9a=false;
    //private String         servidor="192.168.1.109";
    private int port = 5000;
    private ServerSocket server = null;
    private Socket conexion;
    public String cadena="";
    private InetAddress host;
  
}